<a href="https://colab.research.google.com/github/2303A51967/23CSBTB27/blob/main/lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
list={1,5,2,6,7}
list1={3,6,1,8}
print(list)
print(list1)

{1, 2, 5, 6, 7}
{8, 1, 3, 6}


In [4]:
List = ["Greek","For","Greeks"]
List2="my first lab"
List3=4.3
List4=2j+6
List5='My First Lab'
print(type(List2))
print(type(List3))
print(type(List4))
print(type(List5))
print("\nList Items:")
print(List)
print(type(List))
print(List[0])

<class 'str'>
<class 'float'>
<class 'complex'>
<class 'str'>

List Items:
['Greek', 'For', 'Greeks']
<class 'list'>
Greek


In [5]:
List={1:"Greek1",2:'greeks','for':3,'Greek':6}
print("\nList with the use of Mixed Values:")
print(List)
print(type(List))


List with the use of Mixed Values:
{1: 'Greek1', 2: 'greeks', 'for': 3, 'Greek': 6}
<class 'dict'>


In [6]:
import numpy as np
arry=np.array([2,5,3,7,3])
print(arry)
print(type(arry))

[2 5 3 7 3]
<class 'numpy.ndarray'>


In [7]:
import numpy as np
arry=np.array([[2,5],[4,2]])
arry1=np.array([[2,5,4,2],[4,2,1,0]])
arry2=np.array([[2,5,4],[4,2,5],[6,7,8]])
print(arry)
print(arry1)
print(arry2)

[[2 5]
 [4 2]]
[[2 5 4 2]
 [4 2 1 0]]
[[2 5 4]
 [4 2 5]
 [6 7 8]]
